# Generated by Django 2.2.2 on 2019-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190710_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='is_paypal',
            field=models.BooleanField(default=False),
        ),
    ]
