# Generated by Django 2.2.2 on 2020-01-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_campaignchoices_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='referring_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
