# Generated by Django 2.2.2 on 2019-07-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='filename',
            field=models.CharField(default='ting', max_length=120),
            preserve_default=False,
        ),
    ]
