# Generated by Django 2.2.2 on 2019-07-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0003_beat_bpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
