# Generated by Django 2.2.2 on 2019-07-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0004_beat_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='beats/'),
        ),
    ]
