# Generated by Django 2.2.2 on 2019-07-02 17:05

import beatstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0005_beat_cover_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to=beatstore.models.upload_media_path),
        ),
    ]
