# Generated by Django 2.2.2 on 2019-07-02 17:58

import beatstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0006_auto_20190702_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=beatstore.models.upload_media_path),
        ),
    ]
