# Generated by Django 2.2.2 on 2019-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0007_beat_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
