# Generated by Django 2.2.2 on 2019-07-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0009_auto_20190708_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='slug',
        ),
    ]
