# Generated by Django 2.2.2 on 2019-11-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_beat'),
        ('beatstore', '0012_auto_20190708_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standard_lease', to='products.Product'),
        ),
        migrations.AddField(
            model_name='beat',
            name='trackout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trackout_lease', to='products.Product'),
        ),
        migrations.AddField(
            model_name='beat',
            name='unlimited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unlimited_lease', to='products.Product'),
        ),
    ]
