# Generated by Django 2.2.2 on 2019-11-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0013_auto_20191107_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='trackout',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='unlimited',
        ),
    ]
