# Generated by Django 2.2.2 on 2019-11-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0014_auto_20191111_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beat',
        ),
    ]
