# Generated by Django 2.2.2 on 2019-07-18 22:16

import django.core.files.storage
from django.db import migrations, models
import products.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190714_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=storages.backends.s3boto3.S3Boto3Storage(location='protected')), upload_to=products.models.upload_product_file_loc),
        ),
    ]
