# Generated by Django 2.2.2 on 2019-07-18 23:28

import django.core.files.storage
from django.db import migrations, models
import products.models
import splitcloud.AWS.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190718_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=splitcloud.AWS.utils.ProtectedS3Storage), upload_to=products.models.upload_product_file_loc),
        ),
    ]
