# Generated by Django 2.2.2 on 2019-07-19 18:49

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190718_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='d:\\dev\\scp\\static_cdn\\protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
