# Generated by Django 2.2.2 on 2019-11-07 16:37

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('beatstore', '0012_auto_20190708_1320'),
        ('products', '0008_auto_20190719_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='beat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='beatstore.Beat'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='c:\\Users\\Stephen\\Documents\\Dev\\scp\\static_cdn\\protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
