# Generated by Django 2.2.2 on 2019-11-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191107_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='beat',
        ),
    ]
