# Generated by Django 2.2.2 on 2019-11-12 00:31

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_beat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('filename', models.CharField(max_length=120)),
                ('bpm', models.CharField(blank=True, max_length=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to=products.models.upload_media_path)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=products.models.upload_media_path)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standard_lease', to='products.Product')),
                ('trackout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trackout_lease', to='products.Product')),
                ('unlimited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unlimited_lease', to='products.Product')),
            ],
        ),
    ]
