# Generated by Django 2.2.2 on 2020-01-07 17:33

from django.db import migrations, models
import products.models
import splitcloud.AWS.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_beat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=splitcloud.AWS.utils.ProtectedS3Storage(), upload_to=products.models.upload_product_file_loc),
        ),
    ]
