# Generated by Django 2.2.2 on 2020-01-14 00:12

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200107_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_media_path),
        ),
    ]
